### ISSUE TITLE
Hala users as an independent service

### ISSUE THREAD

**Issue by ahasna** [ahasna/issue-tracking#1]
## Overview

`Hala Users` is a service lives an AWS Account that uses `Cognito` to manages users Authentication and Authorisation by using:

- Cognito User Pools
- Cognito Identity Pools

## Task Objectives

- [ ] Create `hala-users` AWS Account
- [ ] Create `Cognito` service, with the following in mind:
    - [ ] there should be both a `user pool` and an `identity pool` per project
    - [ ] leverage **IaC** to create blueprints for every resource needed
